name: Execute SQL scripts on Cloud SQL

on:
  push:
    branches:
      - db-deployment

jobs:
  execute-sql:
    runs-on: ubuntu-latest
    environment: GCP_PROJECT_ID
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      
      - name: Authenticate to cloud sql proxy
        run: |
          gcloud auth application-default login --quiet

      - name: Install MySQL client
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name: Download Cloud SQL Auth Proxy
        run: |
          curl -o cloud-sql-proxy https://dl.google.com/cloudsql/cloud-sql-proxy.linux.amd64
          chmod +x cloud-sql-proxy

      - name: Run SQL scripts on Cloud SQL
        run: |          
          # Run SQL scripts in sequence
          for script in db_drop.sql db_create.sql db_load.sql; do
            echo "▶️ Running $script..."
            mysql -u ${{ secrets.DB_USER }} \
                  -p${{ secrets.DB_PASS }} \
                  -D ${{ secrets.DB_NAME }} \
                  -h 127.0.0.1 \
                  -P 3306 \
                  < src/lib/server/db_schema/$script
          done
