name: Execute SQL scripts on Cloud SQL

on:
  push:
    branches:
      - db-deployment

jobs:
  execute-sql:
    runs-on: ubuntu-latest
    environment: GCP_PROJECT_ID
    steps:
      - name: Checkout code
        uses: actions/checkout@v4      

      - name: Download Cloud SQL Auth Proxy
        run: |
          curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.18.0/cloud-sql-proxy.linux.amd64
          chmod +x cloud-sql-proxy       

      - name: Cloud SQL Proxy Help
        run: |
          ./cloud-sql-proxy --help   

      - name: Start Cloud SQL Auth Proxy
        run: |
          # Save the service account JSON key from secrets to a file
          echo "${{ secrets.GCP_SA_KEY }}" > sa-key.json

          # list files to verify the key is saved
          echo "Listing files in the current directory:"          
          ls -la

          # Build the connection name from secrets
          INSTANCE_CONNECTION_NAME="${{ secrets.GCP_PROJECT_ID }}:${{ secrets.GCP_REGION }}:${{ secrets.DB_INSTANCE }}"          

          # Start the Cloud SQL Auth Proxy with credentials file
          ./cloud-sql-proxy \
            --credentials-file ${{secrets.GCP_SA_KEY}} \
            "$INSTANCE_CONNECTION_NAME" &
          echo $! > proxy.pid

          # Wait until the proxy is ready (check if port 3306 is open)
          for i in {1..10}; do
            if nc -z 127.0.0.1 3306; then
              echo "‚úÖ Cloud SQL Proxy is ready"
              break
            fi
            echo "‚è≥ Waiting for Cloud SQL Proxy..."
            sleep 2
          done


      - name: Run SQL scripts on Cloud SQL
        run: |
          set -e  # Exit immediately if a command fails
          for script in db_drop.sql db_create.sql db_load.sql; do
            echo "‚ñ∂Ô∏è Running $script..."
            mysql -u ${{ secrets.DB_USER }} \
                  -p${{ secrets.DB_PASS }} \
                  -D ${{ secrets.DB_NAME }} \
                  -h 127.0.0.1 \
                  -P 3306 \
                  < src/lib/server/db_schema/$script
          done

      - name: Stop Cloud SQL Auth Proxy and clean up
        run: |
          if [ -f proxy.pid ]; then
            kill $(cat proxy.pid) || true
            echo "üõë Cloud SQL Proxy stopped"
          fi
          rm -f proxy.pid sa-key.json
