name: Execute SQL scripts on Cloud SQL

on:
  push:
    branches:
      - db-deployment

jobs:
  execute-sql:
    runs-on: ubuntu-
    environment: GCP_PROJECT_ID
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Install MySQL client
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name: Start Cloud SQL Auth Proxy
        run: |
          INSTANCE_CONNECTION_NAME="${{ secrets.GCP_PROJECT_ID }}:${{ secrets.GCP_REGION }}:${{ secrets.DB_INSTANCE }}"
          curl -o cloud-sql-proxy https://dl.google.com/cloudsql/cloud-sql-proxy.linux.amd64
          chmod +x cloud-sql-proxy
          ./cloud-sql-proxy ${{ secrets.DB_INSTANCE_CONNECTION_NAME }} &
          sleep 5

      - name: Run SQL scripts
        run: |
          mysql -u ${{ secrets.DB_USER }} \
                -p${{ secrets.DB_PASS }} \
                -D ${{ secrets.DB_NAME }} \
                -h 127.0.0.1 \
                < src/lib/server/db_schema/db_drop.sql

          mysql -u ${{ secrets.DB_USER }} \
                -p${{ secrets.DB_PASS }} \
                -D ${{ secrets.DB_NAME }} \
                -h 127.0.0.1 \
                < src/lib/server/db_schema/db_create.sql

          mysql -u ${{ secrets.DB_USER }} \
                -p${{ secrets.DB_PASS }} \
                -D ${{ secrets.DB_NAME }} \
                -h 127.0.0.1 \
                < src/lib/server/db_schema/db_load.sql
